// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MmuIspApi.Data;

#nullable disable

namespace MmuIspApi.Migrations
{
    [DbContext(typeof(MmuDbContext))]
    [Migration("20260918120000_AddLiveMonitor")]
    partial class AddLiveMonitor
    {
    }
}
