// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MmuIspApi.Data;

#nullable disable

namespace MmuIspApi.Migrations
{
    [DbContext(typeof(MmuDbContext))]
    [Migration("20260929101728_AddStudentExtraFields")]
    partial class AddStudentExtraFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MmuIspApi.Models.Admin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Institutions")
                        .HasColumnType("json");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Permissions")
                        .HasColumnType("json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("MmuIspApi.Models.Cohort", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "SortOrder");

                    b.ToTable("Cohorts");
                });

            modelBuilder.Entity("MmuIspApi.Models.CustomRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomRoles");
                });

            modelBuilder.Entity("MmuIspApi.Models.Institution", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Year")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("MmuIspApi.Models.InstitutionLoginConfig", b =>
                {
                    b.Property<string>("InstitutionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Field1Column")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Field1Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Field1Max")
                        .HasColumnType("int");

                    b.Property<int>("Field1Min")
                        .HasColumnType("int");

                    b.Property<bool>("Field1Required")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Field2Column")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Field2Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Field2Max")
                        .HasColumnType("int");

                    b.Property<int>("Field2Min")
                        .HasColumnType("int");

                    b.Property<bool>("Field2Required")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("InstitutionId");

                    b.ToTable("InstitutionLoginConfigs");
                });

            modelBuilder.Entity("MmuIspApi.Models.LogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Actor")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("MmuIspApi.Models.MonitorConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AbandonMin")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("HeartbeatSec")
                        .HasColumnType("int");

                    b.Property<int>("OfflineSec")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MonitorConfigs");
                });

            modelBuilder.Entity("MmuIspApi.Models.MonitorSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastPausedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PausedSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MonitorSessions");
                });

            modelBuilder.Entity("MmuIspApi.Models.Selection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ArchivedWithTree")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ChoiceCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("PreAssignLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("SourceProportional")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.Property<string>("Tiebreaker")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("TreeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ViewMode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("TreeId");

                    b.ToTable("Selections");
                });

            modelBuilder.Entity("MmuIspApi.Models.SpecialtyNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("AllowFemale")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("AllowMale")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Filters")
                        .HasColumnType("json");

                    b.Property<string>("GroupTiebreakers")
                        .HasColumnType("json");

                    b.Property<string>("Groups")
                        .HasColumnType("json");

                    b.Property<int?>("LiseyQuota")
                        .HasColumnType("int");

                    b.Property<int?>("MaxFemale")
                        .HasColumnType("int");

                    b.Property<int?>("MaxMale")
                        .HasColumnType("int");

                    b.Property<int?>("MulkiQuota")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Quota")
                        .HasColumnType("int");

                    b.Property<string>("QuotaMode")
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Tiebreaker")
                        .HasColumnType("json");

                    b.Property<string>("TreeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TreeId", "ParentId");

                    b.ToTable("SpecialtyNodes");
                });

            modelBuilder.Entity("MmuIspApi.Models.SpecialtyTree", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CohortId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LevelNames")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("SourceProportional")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Year")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("SpecialtyTrees");
                });

            modelBuilder.Entity("MmuIspApi.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BranchByLevel")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int?>("ChoiceNum")
                        .HasColumnType("int");

                    b.Property<string>("CohortId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExtraFields")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Fin")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .HasColumnType("longtext");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Packet")
                        .HasColumnType("int");

                    b.Property<string>("ParentName")
                        .HasColumnType("longtext");

                    b.Property<string>("PlacedSelectionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PlacedSpecialty")
                        .HasColumnType("longtext");

                    b.Property<string>("PlacedSpecialtyId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrintStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("WorkNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Year")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Fin");

                    b.HasIndex("PlacedSelectionId");

                    b.HasIndex("PlacedSpecialtyId");

                    b.HasIndex("CohortId", "WorkNumber");

                    b.HasIndex("InstitutionId", "WorkNumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MmuIspApi.Models.StudentPresence", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Fin")
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .HasColumnType("longtext");

                    b.Property<string>("InstitutionId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StudentId");

                    b.HasIndex("SessionId");

                    b.ToTable("StudentPresences");
                });

            modelBuilder.Entity("MmuIspApi.Models.Submission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("SelectionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SelectionId");

                    b.HasIndex("UserId", "SelectionId")
                        .IsUnique();

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("MmuIspApi.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PrioritySubjects")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("RedirectDelaySec")
                        .HasColumnType("int");

                    b.Property<string>("SubmitNotice")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("MmuIspApi.Models.TreeArchive", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.ToTable("TreeArchives");
                });

            modelBuilder.Entity("MmuIspApi.Models.UserArchive", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.ToTable("UserArchives");
                });

            modelBuilder.Entity("MmuIspApi.Models.Cohort", b =>
                {
                    b.HasOne("MmuIspApi.Models.Institution", "Institution")
                        .WithMany("Cohorts")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("MmuIspApi.Models.InstitutionLoginConfig", b =>
                {
                    b.HasOne("MmuIspApi.Models.Institution", "Institution")
                        .WithOne()
                        .HasForeignKey("MmuIspApi.Models.InstitutionLoginConfig", "InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("MmuIspApi.Models.Selection", b =>
                {
                    b.HasOne("MmuIspApi.Models.Institution", "Institution")
                        .WithMany("Selections")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MmuIspApi.Models.SpecialtyTree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("MmuIspApi.Models.SpecialtyNode", b =>
                {
                    b.HasOne("MmuIspApi.Models.SpecialtyNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MmuIspApi.Models.SpecialtyTree", "Tree")
                        .WithMany("Nodes")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("MmuIspApi.Models.SpecialtyTree", b =>
                {
                    b.HasOne("MmuIspApi.Models.Cohort", "Cohort")
                        .WithMany("SpecialtyTrees")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MmuIspApi.Models.Institution", "Institution")
                        .WithMany("SpecialtyTrees")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("MmuIspApi.Models.Student", b =>
                {
                    b.HasOne("MmuIspApi.Models.Cohort", "Cohort")
                        .WithMany("Students")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MmuIspApi.Models.Institution", "Institution")
                        .WithMany("Students")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MmuIspApi.Models.Selection", "PlacedSelection")
                        .WithMany()
                        .HasForeignKey("PlacedSelectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MmuIspApi.Models.SpecialtyNode", "PlacedSpecialtyNode")
                        .WithMany()
                        .HasForeignKey("PlacedSpecialtyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cohort");

                    b.Navigation("Institution");

                    b.Navigation("PlacedSelection");

                    b.Navigation("PlacedSpecialtyNode");
                });

            modelBuilder.Entity("MmuIspApi.Models.Submission", b =>
                {
                    b.HasOne("MmuIspApi.Models.Selection", "Selection")
                        .WithMany("Submissions")
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MmuIspApi.Models.Student", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Selection");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MmuIspApi.Models.Cohort", b =>
                {
                    b.Navigation("SpecialtyTrees");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MmuIspApi.Models.Institution", b =>
                {
                    b.Navigation("Cohorts");

                    b.Navigation("Selections");

                    b.Navigation("SpecialtyTrees");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MmuIspApi.Models.Selection", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("MmuIspApi.Models.SpecialtyNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MmuIspApi.Models.SpecialtyTree", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("MmuIspApi.Models.Student", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
